### PR TITLE
Fix Build Failures

### PR DESCRIPTION
**Pull request by maxinbjohn**
Fix for various build failures caused by updates in the kernel and u-boot build in oe-core fido branch.

### CODE REVIEW

**Comment by koenkooi** [comment]
please fix your commit messages to specify which OE-core branches this is for and remove references to poky.

**Comment by maxinbjohn** [comment]
Thanks for the comments. I will remove the reference to poky and re-create the pull request.

**Comment by maxinbjohn** [comment]
Updated the commit messages as per the review comment.

**Comment by maxinbjohn** [comment]
gentle ping ..

**Pull request merged**
